version: 2.1.4.{build}
configuration: Release
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME".TrimStart("v")
    }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  NugetApiKey:
    secure: coCGHSV1BluFzO5o8njBGZ9aS33VrklF+4geB+9U5NPiQSbntUcywtOXKGIIc4KQ
  SnkSecret:
    secure: j9oVsjzAy5p4Te5FdRAuZQ==
install:
- ps: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe

    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      nuget install secure-file -ExcludeVersion
      .\secure-file\tools\secure-file.exe -decrypt .\AppVeyorBuild\AppVeyorBuilder.snk.enc -secret $env:SnkSecret -out .\AppVeyorBuild\AppVeyorBuild.snk
    }
before_build:
- ps: >-
    nuget restore


    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {
      $filepath = ".\AppVeyorBuild\Properties\AssemblyInfo.cs"
      # Remove any InternalsVisibleTo atrributes
      (Get-Content $filepath) | Where { $_ -notmatch "^\[assembly: InternalsVisibleTo" } | out-file $filepath
      # Add Signing key attribute
      Add-Content $filepath '[assembly: AssemblyKeyFile("AppVeyorBuild.snk")]'
    }
build:
  verbosity: minimal
after_build:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {
      nuget pack .\AppVeyorBuild\AppVeyorBuild.nuspec -Properties "Configuration=Release;Platform=AnyCPU;" -version "$env:APPVEYOR_BUILD_VERSION"
      nuget push *.nupkg $env:NugetApiKey -Source https://www.nuget.org/api/v2/package
    }
test: off
artifacts:
- path: .\AppVeyorBuild\bin
  name: AppVeyorBuild
deploy:
- provider: GitHub
  auth_token:
    secure: SKZPuqPpuYCGDlPa2hEJ6NmjNBWJ9J60/kM7Y5cEtvm3EHrYX5j3VhV2KV5os5gA
  on:
    appveyor_repo_tag: true
